import MyAppBar from "@/components/common/MyAppBar";
import { CustomCard } from "@/styles/mui/customComponents";

import { darkTheme, lightTheme } from "@/styles/mui/theme";
import {
  Avatar,
  Box,
  Container,
  CssBaseline,
  Grid,
  ThemeProvider,
  Typography,
} from "@mui/material";
import Head from "next/head";

export default function Blog() {
  return (
    <>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <Head>
          <title>My Blog Posts | My Favourite Movies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MyAppBar />

        <Container maxWidth="xl">
            Blog Page
        </Container>
      </ThemeProvider>
    </>
  );
}
