import MyAppBar from "@/components/common/MyAppBar";
import { CustomCard } from "@/styles/mui/customComponents";

import { darkTheme, lightTheme } from "@/styles/mui/theme";
import {
  Avatar,
  Box,
  Container,
  CssBaseline,
  Grid,
  ThemeProvider,
  Typography,
} from "@mui/material";
import Head from "next/head";

export default function Home() {
  const movies = [
    {
      name: "Avengers",
      img: "https://imgix.ranker.com/list_img_v2/18864/1998864/original/the-best-the-avengers-quotes",
      desc: "Directed By Joss Whedon",
    },
    {
      name: "Terminator",
      img: "https://townsquare.media/site/295/files/2019/10/Terminator-Orion.jpg?w=1200&h=0&zc=1&s=0&a=t&q=89",
      desc: "Directed By James Cameron",
    },
    {
      name: "Inception",
      img: "https://images5.alphacoders.com/112/1122037.jpg",
      desc: "Directed By Chris Nolan",
    },
    {
      name: "Jurassic Park",
      img: "https://i.ytimg.com/vi/Rc_i5TKdmhs/maxresdefault.jpg",
      desc: "Directed By Steven Spielberg",
    },
    {
      name: "Superman",
      img: "https://image.tmdb.org/t/p/original/3rGzY1RaVgWIP4GuOTwdHwHXSgM.jpg",
      desc: "Directed by James Gunn",
    },
  ];
  return (
    <>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <Head>
          <title>My Favourite Movies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MyAppBar />

        <Container maxWidth="xl">
          <Box
            sx={{
              width: "100%",
              marginTop: "70px",
              marginBottom: "70px",
            }}
          >
            <center>
              <Avatar
                alt="Thanos by Josh Brolin"
                src="https://www.ericjuneaubooks.com/wp-content/uploads/2023/02/thanos_marvel_square-300x300.jpg"
                sx={{ width: 120, height: 120 }}
              />
            </center>
          </Box>
          <center>
            <Typography variant="h4" gutterBottom>
              The List of Movies
            </Typography>
          </center>

          <Grid
            container
            spacing={2}
            sx={{ marginBottom: "70px", marginTop: "70px" }}
          >
            {movies.map((movie) => (
              <Grid size={4}>
                <CustomCard name={movie.name} img={movie.img} desc={movie.desc} />
              </Grid>
            ))}
          </Grid>
        </Container>
      </ThemeProvider>
    </>
  );
}
