import MyAppBar from "@/components/common/MyAppBar";
import { CustomCard } from "@/styles/mui/customComponents";

import { darkTheme, lightTheme } from "@/styles/mui/theme";
import {
  Avatar,
  Box,
  Button,
  Container,
  CssBaseline,
  Grid,
  ThemeProvider,
  Typography,
} from "@mui/material";
import axios from "axios"; // npm i axios
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  // useState Hook
  const [visible, setVisible] = useState(true);
  const [movies, setMovies] = useState(null);

  // useEffect Hook
  useEffect(() => {
    fetchMovies();
  }, []);

  const fetchMovies = async () => {
    try {
      const response = await axios.get("/api/v1/get/movies");
      console.log("response: ", response.data);

      setMovies(response.data);
    } catch (error) {
      console.error("ERROR: ", error);
    }
  };

  return (
    <>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <Head>
          <title>My Favourite Movies</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <MyAppBar />

        <Container maxWidth="xl">
          <Box
            sx={{
              width: "100%",
              marginTop: "70px",
              marginBottom: "70px",
            }}
          >
            <center>
              {visible ? (
                <Avatar
                  alt="Thanos by Josh Brolin"
                  src="https://www.ericjuneaubooks.com/wp-content/uploads/2023/02/thanos_marvel_square-300x300.jpg"
                  sx={{ width: 120, height: 120 }}
                />
              ) : (
                <></>
              )}
            </center>
          </Box>
          <center>
            <Typography variant="h4" gutterBottom>
              The List of Movies
            </Typography>
            {/* <Button onClick={() => setVisible(!visible)}>Visible/Not Visible</Button> */}
            {/* <Button onClick={() => fetchMovies()}>Fetch Movies</Button> */}
          </center>

          <Grid
            container
            spacing={2}
            sx={{ marginBottom: "70px", marginTop: "70px" }}
          >
            {movies ? (
              movies.response.map((movie, i) => (
                <Grid size={3} key={i}>
                  <CustomCard
                    title={movie.title}
                    imageUrl={movie.imageUrl}
                    description={movie.description}
                  />
                </Grid>
              ))
            ) : (
              <></>
            )}
          </Grid>
        </Container>
      </ThemeProvider>
    </>
  );
}
