import MyAppBar from "@/components/common/MyAppBar";
import { CustomCard } from "@/styles/mui/customComponents";

import { darkTheme, lightTheme } from "@/styles/mui/theme";
import {
  Avatar,
  Box,
  Button,
  Container,
  CssBaseline,
  Grid,
  ThemeProvider,
  Typography,
} from "@mui/material";
import axios from "axios"; // npm i axios
import Head from "next/head";
import { useEffect, useState } from "react";

import Login from "../components/common/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>Login | My Favourite Movies</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={lightTheme}>
        <CssBaseline />
        <MyAppBar />

        <Login />
      </ThemeProvider>
    </>
  );
}
